server:
  port: 8100

spring:
  application:
    name: currency-conversion-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/currency
          jwk-set-uri: http://keycloak:8080/realms/currency/protocol/openid-connect/certs
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 3000
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://naming-server:8761/eureka